spring:
  flyway:
    locations: classpath:db/migration,classpath:db/demo
  security:
    user:
      name: ${DEMO_USER:user}
      password: ${DEMO_PASSWORD:password}

app:
  security:
    api-key: ${API_KEY:demo-api-key}
    session-timeout-in-minutes: ${SESSION_TIMEOUT_IN_MINUTES:60}
  outbox:
    webhook:
      enabled: ${OUTBOX_WEBHOOK_ENABLED:true}
      base-url: ${OUTBOX_WEBHOOK_BASE_URL:http://localhost:8080/api/demo/webhook}