CREATE TABLE product (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    price DOUBLE,
    active BOOLEAN,
    activation_date TIMESTAMP
);

CREATE TABLE product_image (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(255),
    product_id BIGINT,
    CONSTRAINT fk_product
        FOREIGN KEY (product_id)
        REFERENCES product(id)
);

CREATE TABLE product_details (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(255),
    sku VARCHAR(255),
    warranty VARCHAR(255),
    product_id BIGINT UNIQUE,
    
    CONSTRAINT fk_product_details_product
        FOREIGN KEY (product_id)
        REFERENCES product (id)
);
