-- ===========================
-- CATEGORY
-- ===========================
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


-- ===========================
-- PRODUCT_DETAILS
-- ===========================
ALTER TABLE product_details ADD COLUMN category_id BIGINT;

ALTER TABLE product_details
ADD CONSTRAINT fk_product_details_category
FOREIGN KEY (category_id) REFERENCES category(id);


-- ===========================
-- INDICI (performance)
-- ===========================
CREATE INDEX idx_product_details_category
    ON product_details(category_id);

CREATE INDEX idx_product_image_product
    ON product_image(product_id);