-- Tables
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    status VARCHAR(50),
    company_id BIGINT,
    street VARCHAR(255),
    city VARCHAR(255),
    zip_code VARCHAR(50),
    country VARCHAR(100),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT,
    deleted BOOLEAN,
    CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    amount DOUBLE PRECISION,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Sequences
--CREATE SEQUENCE user_seq START 1 INCREMENT 1;
--CREATE SEQUENCE order_seq START 1 INCREMENT 1;
--CREATE SEQUENCE company_seq START 1 INCREMENT 1;