ALTER TABLE orders ADD COLUMN created_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN created_by VARCHAR(100);
ALTER TABLE orders ADD COLUMN last_modified_by VARCHAR(100);
